services:
  db:
    image: pgvector/pgvector:pg16
    container_name: self-server-db
    restart: unless-stopped
    env_file:
      ../.env
    ports:
      # local access
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # run sql files in db/init/ once on first container start
      - ../db/init:/docker-entrypoint-initdb.d:ro # set read only

    healthcheck:
      # $$ for expansion to the container shell
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
